### ISSUE TITLE
Import to android

### ISSUE THREAD

**Issue by Francois284Modz** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#1]
Hello i have a question but can this menu ne import to android device ? Or not can you make a version that can be use on android

**Comment by joeyjurjens** [comment]
No, this is written in Objective-C, which does not work on Android.
If you want a Mod Menu for android, this is the only public menu:
https://github.com/MrIkso/FloatingModMenu

I plan on creating one for android, but that won't be soon.
