### ISSUE TITLE
Crash when closing the game.

### ISSUE THREAD

**Issue by AgarioModMenu** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#15]
I created a mod menu for a game and thank you for your template. But when I or someone else closes the game then we got crash notification. I checked all codes and I didn’t found any issues on my code. So it seems like it's with the template.

**Comment by joeyjurjens** [comment]
I'm unsure what you mean and with this information I can't reproduce the error.

**Comment by bR34Kr** [comment]
@AgarioModMenu Try sending your Tweak.xm and/or the whole project you have setup so the issue can be analyzed better. Saying that some unknown app crashes for an unknown reason doesn’t really pinpoint the issue.

**Comment by AgarioModMenu** [comment]
Ok where can I send you the project?

**Comment by bR34Kr** [comment]
On this issue page. You can upload files on here by drag & dropping them.

**Comment by joeyjurjens** [comment]
If you don't feel like sharing the project so openly due unique hacks etc, you can send them to my discord: Joey#0309 .

I won't share them, I'd just use it to reproduce the issue.

**Comment by joeyjurjens** [comment]
This issue also happened when no mod menu was installed, closing.
