### ISSUE TITLE
modmenu support substitute or A12 device??

### ISSUE THREAD

**Issue by kuteteen** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#2]
hello TED2!!
modmenu support substitute or A12 device??

**Comment by joeyjurjens** [comment]
Hello,
Yes it does support substitute and can support A12 devices.

To make it compatible with A12 devices, you'll need to add arm64e in your makefile, which can only be compiled on a macOS/linux system or a A12 device that can run and compile with theos (which is none atm).
