### ISSUE TITLE
Error setting mod menu

### ISSUE THREAD

**Issue by Ducmanhvn** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#25]
What should i do to fix this error,im use theos13.1 and ios13.3.1.BIG THANKS

![3FFB1D40-DB94-4439-9155-719FFD18926F](https://user-images.githubusercontent.com/71457494/93502158-93bbc100-f940-11ea-95f1-94a6ac0e7b8f.png)

> dyld: Library not loaded: /usr/lib/libplist.3.dylib   
  Referenced from: /usr/bin/ldid                      
  Reason: Incompatible library version: ldid requires version 7.0.0 or later, but libplist.3.dylib provides version 5.0.0                                           
bash: line 1: 11601 Abort trap: 6           CODESIGN_ALLOCATE=codesign_allocate ldid -S/var/theos/entitlements.xml "/var/mobile/kk/.theos/obj/@@PROJECTNAME@@.dylib.93e8684b.unsigned"                                     
make[2]: *** [/var/theos/makefiles/instance/library.mk:51: /var/mobile/kk/.theos/obj/@@PROJECTNAME@@.dylib] Error 134                                               
rm /var/mobile/kk/.theos/obj/@@PROJECTNAME@@.dylib.93e8684b.unsigned                                         
make[1]: *** [/var/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2                    
make: *** [/var/theos/makefiles/master/rules.mk:116: @@PROJECTNAME@@.all.tweak.variables] Error 2

**Comment by joeyjurjens** [comment]
Have you installed the Theos Dependencies and Darwin CC Tools from Cydia?

**Comment by Buiduc12** [comment]
Tôi lên làm gì để khắc phục lỗi này,

![81940DD8-189C-4712-87DF-8D584F95C83D](https://user-images.githubusercontent.com/91523002/150782962-e989b50b-521d-4c56-a8cf-ef4d2c79d732.png)
