### ISSUE TITLE
Filza can’t open files over ~2KiB, i.e everything

### ISSUE THREAD

**Issue by TheAwesome98-Real** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#26]
Filza is unable to open the ~400KiB sample.xm file, which is what I want to edit. Do you know any good iOS code editors or a way to work around this?

**Comment by TheAwesome98-Real** [comment]
It works with the 2-3KiB ones but not the 24KiB one ¯\\\_(ツ)_/¯

**Comment by joeyjurjens** [comment]
I do not. Coding on pc is suggested anyways.

**Comment by TheAwesome98-Real** [comment]
Okay
