### ISSUE TITLE
vector,string not found in kittymemory header

### ISSUE THREAD

**Issue by TheAwesome98-Real** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#29]
when I make, string and vector are not found

they don’t have like .c or .h, literally just string and vector

EDIT: added “are” cause grammar

**Comment by joeyjurjens** [comment]
Did you link your SDK's correctly in your Makefile? And did you download the theos-sdks from github? Those are recommended.

**Comment by TheAwesome98-Real** [comment]
> Did you link your SDK's correctly in your Makefile? And did you download the theos-sdks from github? Those are recommended.

Yes and yes
