### ISSUE TITLE
KittyMemory/initializer_list:33:10: fatal error:        'bits/c++config.h' file not found #include <bits/c++config.h>    

### ISSUE THREAD

**Issue by simtechnos** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#4]
I am doing this on mac so a lil help will be great

**Comment by TheArmKing** [comment]
delete the initializer_list file in KittyMemory, some errors will come up regarding where it was being imported from. Send that

**Comment by joeyjurjens** [comment]
This issue was due the fact he was running an old template. Current template does no longer use a initializer_list file from the project.

**Comment by cuongsino** [comment]
How to fix? Please help
