### ISSUE TITLE
Tôi lên làm gì để  khắc phục lôi này

### ISSUE THREAD

**Issue by Buiduc12** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#41]
![DEF46681-4F7A-4E51-A9D2-56175A2D7C9A](https://user-images.githubusercontent.com/91523002/150783127-00513c89-7b0f-45a8-b604-ec4352a635a0.png)

**Comment by joeyjurjens** [comment]
I suggest you to read through the readme of this repo, as you're creating switches the old way (which is no longer supported). The readme shows how to create switches and also tells you how to setup theos.
