### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by UnknownXXX000** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#45]
Hello
Could you please help me
Im working on a mod menu and there are some issues with compilation

> 

Log
`iPhone:~ root# cd /var/root/modmenu1
iPhone:~/modmenu1 root# MP
===> Setting SYSROOT to /var/root/theos/sdks/iPhoneOS11.4.sdk/...
/usr/local/bin/curl: 1: /usr/bin/curl: not found
> Making all for tweak modmenu1…
===> Setting SYSROOT to /var/root/theos/sdks/iPhoneOS11.4.sdk/...
===> Setting SYSROOT to /var/root/theos/sdks/iPhoneOS11.4.sdk/...
===> Setting SYSROOT to /var/root/theos/sdks/iPhoneOS11.4.sdk/...
==> Preprocessing Tweak.xm…
==> Compiling KittyMemory/KittyMemory.cpp (arm64)…
In file included from KittyMemory/KittyMemory.cpp:9:
KittyMemory/KittyMemory.hpp:13:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
make[3]: *** [/var/root/theos/makefiles/instance/rules.mk:237: /var/root/modmenu1/.theos/obj/arm64/KittyMemory/KittyMemory.cpp.7656cb73.o] Error 1
make[3]: *** Waiting for unfinished jobs....
==> Compiling Menu.mm (arm64)…
In file included from Menu.mm:10:
In file included from ./Menu.h:10:
./KittyMemory/MemoryPatch.hpp:9:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
make[3]: *** [/var/root/theos/makefiles/instance/rules.mk:201: /var/root/modmenu1/.theos/obj/arm64/Menu.mm.7656cb73.o] Error 1
rm /var/root/modmenu1/.theos/obj/arm64/Tweak.xm.mm
make[2]: *** [/var/root/theos/makefiles/instance/library.mk:52: /var/root/modmenu1/.theos/obj/arm64/modmenu1.dylib] Error 2
make[1]: *** [/var/root/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/var/root/theos/makefiles/master/rules.mk:117: modmenu1.all.tweak.variables] Error 2
iPhone:~/modmenu1 root#`

**Comment by ForestOfGold** [comment]
Try copying the files from
`yourSDK/usr/include/c++/4.2.1/`
to
$THEOS/include
