### ISSUE TITLE
This mod menu seems broken on iOS 15 jailbreak (XinaA15)

### ISSUE THREAD

**Issue by 34306** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#47]
As title, when you press on patching offset on iOS 15 jailbroken by Xina, it's crash. Do you have any idea to fix that?

**Comment by joeyjurjens** [comment]
Hi, I don't have a device on iOS 15 with jailbreak anymore. 

But could you try replacing the folder "KittyMemory" with the new one from here: https://github.com/MJx0/KittyMemory

That might work, if it does, let me know please so I can update that here.

Thank you.

**Comment by 34306** [comment]
I'll give it a test. Report that later!
Btw ty!

**Comment by impapas** [comment]
> I'll give it a test. Report that later! Btw ty!

did it ever work??

**Comment by qasimaziz5** [comment]
![image](https://user-images.githubusercontent.com/117679583/211973552-7b481f2c-8514-435e-b865-3213b6787547.png)

**Comment by joeyjurjens** [comment]
> ![image](https://user-images.githubusercontent.com/117679583/211973552-7b481f2c-8514-435e-b865-3213b6787547.png)

Try it with Filza / iFile

**Comment by 34306** [comment]
> > I'll give it a test. Report that later! Btw ty!
> 
> Hi, did you happen to try this? Would love to know if that fixes the issue.

Tried the new KittyMemory, it work with game with UnityFramework.framework but the game without UnityFramework is not working. (I'm testing Cytus 2 [UnityFramework.framework/UnityFramework] with offset unlock all character and work. But I try Genshin Impact [NULL or GenshinImpact] with No CD offset and hook, it crash at the time I press the function button)

**Comment by joeyjurjens** [comment]
> > > I'll give it a test. Report that later! Btw ty!
> > 
> > 
> > Hi, did you happen to try this? Would love to know if that fixes the issue.
> 
> Tried the new KittyMemory, it work with game with UnityFramework.framework but the game without UnityFramework is not working. (I'm testing Cytus 2 [UnityFramework.framework/UnityFramework] with offset unlock all character and work. But I try Genshin Impact [NULL or GenshinImpact] with No CD offset and hook, it crash at the time I press the function button)

That's a pitty. Unfortunately I don't have a device on iOS 15 to test this on, so as of now I'm unable to fix this.
I'll mark this issue as help-needed, might someone know a fix, that person may do this.

**Comment by 34306** [comment]
Alright. Thanks for your help!

**Comment by cuzeus** [comment]
Im having same issue on palera1n -c ios 15.6 i tried changing KittyMemory but still same.When i check the crash logs i see that ios terminate the app after 20 seconds  because tweak make game into infinite looping. I heard some other mod menus working fine so im not sure if its about my jb. If u can take a look it would be nice

**Comment by cuzeus** [comment]
idk how but like 1 of the 100 tries (like after rejb) it doesnt crash and works but i couldnt understand what cause it

**Comment by joeyjurjens** [comment]
@34306 
I updated my menu to support the palera1n jailbreak, but you can give the new version a try for the Xina jailbreak as well;
https://github.com/joeyjurjens/iOS-Mod-Menu-Template-for-Theos/releases/tag/1.0.0

**Comment by 34306** [comment]
@joeyjurjens I'm testing for palera1n rn. It works fine. I'll test on Xina later. Tysm

**Comment by joeyjurjens** [comment]
> @joeyjurjens I'm testing for palera1n rn. It works fine. I'll test on Xina later. Tysm

Cool. I've some reports from others stating it's fixed in the Xina jailbreak as well. Waiting for your response until i close this issue.

**Comment by 34306** [comment]
Oh I didn't test mshook. It seems mshook crashed on Xina, only patching offset work...
