### ISSUE TITLE
Slider toggle 

### ISSUE THREAD

**Issue by SirEnvious** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#5]
when testing a menu and  sometimes the sliders will show that they are enabled but will actually be disabled, this happens for the other way too, they can show disabled but be enabled

**Comment by joeyjurjens** [comment]
I'll look into this tonight.

**Comment by joeyjurjens** [comment]
This issue has been fixed in [This commit](https://github.com/joeyjurjens/iOS-Mod-Menu-Template-for-Theos/commit/4ba3ff4ba96e780c6fe317f64ea563653f9573f2)

Make sure you've a updated template.
