### ISSUE TITLE
IPA Injection

### ISSUE THREAD

**Issue by syto203** [joeyjurjens/iOS-Mod-Menu-Template-for-Theos#6]
injecting into an ipa crashes the app after the credits pop up. anyway to fix that ?
iOS 13.3-iPX-Jailbroken-checkra1n

edit: forgot to remove the auto patch offset form template. it still crashes when tapping the teddy bear to open the menu.
edit2: removing all switches stops the crash.

**Comment by joeyjurjens** [comment]
This menu was build and tested for jailbroken hacks only, patchOffset, OffsetSwitch won't work due the fact you can't do that on NJB devices. A normal switch should work however, have you tested that?

**Comment by joeyjurjens** [comment]
Gonna close this issue as this isn't really what I built the template for.

**Comment by zakhoy** [comment]
I can’t see mode manue on the game it doesn’t show up in the game

**Comment by zakhoy** [comment]
Any help please
